# Generated by Django 3.1.2 on 2020-11-14 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('moving_time', models.PositiveIntegerField(null=True)),
                ('elapsed_time', models.PositiveIntegerField(null=True)),
                ('total_elevation_gain', models.FloatField(null=True)),
                ('activity_type', models.CharField(max_length=30, null=True)),
                ('average_speed', models.FloatField(null=True)),
                ('max_speed', models.FloatField(null=True)),
                ('elev_high', models.FloatField(null=True)),
                ('elev_low', models.FloatField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
