# Generated by Django 3.1.2 on 2020-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_githonfee_rewardhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
